INSERT INTO `people` (`name`,`killer`, `sex`) VALUES
('Marcial','le ha clavado un boli a', 'M'),
('Pastor','ha desustructurado la familia de', 'M'),
('Silvia','le ha puesto los cuernos a', 'F'),
('Juanjo','se ha emborrachado y se la ha liado a', 'M'),
('Gerardo','ha contado el mayor secreto de', 'M'),
('Leti','ha tenido un orgasmo al reirse de', 'F'),
('Rita','le ha partido la cabeza con un bordillo a', 'F'),
('Rafa','le ha quemado la sangre a', 'M'),
('Lopez','ha descuartizado a', 'M'),
('Kimari','ha tirado por las escaleras a', 'M'),
('Lucia','ha integrado de una hostia a', 'F'),
('Beni', 'le ha pegado un bocado en la yugular a', 'F'),
('Ivan', 'le ha picado el mechero a', 'M'),
('Boni', 'le ha puesto la inyeccion letal a', 'F'),
('Pepis','ha atropellado con el navara a', 'M'),
('Elena Cullar','ha envenenado a', 'F'),
('Miriam Tercera','ha peusto doramion a', 'F'),
('Vendrell','le ha robado el/la novio/a a', 'M'),
('Dario','ha hecho un caballito en la cara de', 'M'),
('Alejandro Pupu','le hizo el alce en celo a', 'M'),
('Sara','le ha pegado 4 voces bien dadas a', 'F'),
('Hermogenes','ha dicho que manda el a', 'M'),
('Asentos','ha llamado desgrasiao de mierda a', 'F'),
('Felipe','ha aplastado con el biceps a', 'M'),
('Vator','le ha dado un croche a', 'M'),
('Cristina','ha castigado a', 'F'),
('Angel','ha estrangulado con los pies a', 'M'),
('Juande','le ha lanzado un hechizo a', 'M'),
('Cifuentes','ha denunciado a la policia local a', 'M'),
('Marta Squad','le ha inyectado aire en las venas a', 'F'),
('Marian','ha quemado con el cigarro hasta la muerte a', 'F'),
('Andrea','le ha tirado la botella de Larios a', 'F'),
('Sus','le ha echado un mal de ojo a', 'M'),
('Nolo','le ha partido las piernas a', 'M'),
('Tony','ha atravesado con la katana a', 'M'),
('Nerea','le ha puesto un helado caducado a', 'F'),
('Samu','le ha dado un beso de la muerte a', 'M'),
('Javi Roldan','le ha tirado la caña a', 'M'),
('Vigara','ha estrangulado con la bandera de España a', 'F'),
('Esme','le ha revanado el cuello con una hoz a', 'F'),
('Arnau','se ha quedado con el dinero de', 'M'),
('Aguayo','le ha metido fuego a', 'M'),
('Jose Carlos','ha atacado con una patada voladora a', 'M'),
('Elena Belicena','le ha echado acido en la cara a', 'F'),
('Renzo','le ha metido una rafaga de tiros a', 'M'),
('Mauricio','ha deborado vivo a', 'M'),
('Marta Boobs','le ha clavado un compas en los ojos a', 'F'),
('Juanka','le ha rajado las venas con la mariposa a', 'M'),
('Marta Pupu','le ha vendido una bolsa de palomitas caducadas a', 'F'),
('Ara','ha hervido vivo a', 'F'),
('Irene','le ha refactorizado la cara de un guantazo a', 'F'),
('Irene Leon','ha cultivado Maria en el pecho de', 'F'),
('Malena','ha hecho una barbacoa con su madre y', 'F'),
('Jose Jesus','le ha dado de su doble V a', 'M'),
('Alberto','le ha partido el brazo a', 'M'),
('PeopleRaper','le ha pagafanteado una BMX bomba a', 'M');