INSERT INTO `people` (`name`) VALUES ('Marcial'),
('Pastor'),
('Silvia'),
('Juanjo'),
('Gerardo'),
('Leti'),
('Rita'),
('Rafa'),
('Lopez'),
('Kimari'),
('Lucia'),
('Beni'),
('Ivan'),
('Boni'),
('Pepis'),
('Elena Cullar'),
('Miriam Tercera'),
('Vendrell'),
('Dario'),
('Alejandro Pupu'),
('Sara'),
('Hermogenes'),
('Asentos'),
('Felipe'),
('Vator'),
('Cristina'),
('Angel'),
('Juande'),
('Cifuentes'),
('Marta Squad'),
('Marian'),
('Andrea'),
('Sus'),
('Nolo'),
('Tony'),
('Nerea'),
('Samu'),
('Javi Roldan'),
('Vigara'),
('Esme'),
('Arnau'),
('Aguayo'),
('Jose Carlos'),
('Elena Belicena'),
('Renzo'),
('Mauricio'),
('Marta Boobs'),
('Juanka'),
('Marta Pupu'),
('Ara'),
('Irene'),
('Irene Leon'),
('Malena'),
('Jose Jesus'),
('Alberto'),
('PeopleRaper'),
('Lococo'),
('Inma');

INSERT INTO `formas`(`people`, `forma`) VALUES 
(1,'le ha clavado un boli a'),
(2,'ha desustructurado la familia de'),
(2,'le desfigura la cara a'),
(2,'deja embarazada a'),
(3,'le ha puesto los cuernos a'),
(3,'lanza un bebe bomba a'),
(4,'se ha emborrachado y se la ha liado a'),
(5,'ha contado el mayor secreto de'),
(6,'ha tenido un orgasmo al reirse de'),
(7,'le ha partido la cabeza con un bordillo a'),
(8,'le ha quemado la sangre a'),
(8,'electrocuta a'),
(9,'hackea a'),
(9,'programa la muerte agónica de'),
(9,'programa la muerte agónica de'),
(10,'ha tirado por las escaleras a'),
(11,'ha integrado de una hostia a'),
(12,'le ha pegado un bocado en la yugular a'),
(12,'lanza la cruz de los gitanos a'),
(13,'le ha picado el mechero a'),
(13,'gana comiendo pizzas del Dominos a'),
(14,'le ha puesto la inyeccion letal a'),
(14,'inducimos un coma a'),
(15,'ha atropellado con el navara a'),
(16,'ha envenenado a'),
(16,'lanza tomates mutantes a'),
(17,'ha puesto doramion a'),
(18,'le ha robado el/la novio/a a'),
(19,'ha hecho un caballito en la cara de'),
(20,'le hizo el alce en celo a'),
(21,'le ha pegado 4 voces bien dadas a'),
(22,'ha dicho que manda el a'),
(23,'ha llamado desgrasiao de mierda a'),
(24,'ha aplastado con el biceps a'),
(25,'le ha dado un croche a'),
(26,'ha castigado a'),
(27,'ha estrangulado con los pies a'),
(27,'sonámbulo echa del bot a'),
(28,'le ha lanzado un hechizo a'),
(28,'le clava la espada maestra a'),
(29,'ha denunciado a la policia local a'),
(30,'le ha inyectado aire en las venas a'),
(30,'mete una sonda por el culo a'),
(31,'ha quemado con el cigarro hasta la muerte a'),
(31,'asfixia con un abrazo a'),
(32,'le ha tirado la botella de Larios a'),
(33,'le ha echado un mal de ojo a'),
(34,'le ha partido las piernas a'),
(35,'ha atravesado con la katana a'),
(35,'le ha derramado una cerveza en la espalda a'),
(36,'le ha puesto un helado caducado a'),
(37,'le ha dado un beso de la muerte a'),
(38,'le ha tirado la caña a'),
(39,'ha estrangulado con la bandera de España a'),
(40,'le ha revanado el cuello con una hoz a'),
(41,'se ha quedado con el dinero de'),
(42,'le ha metido fuego a'),
(43,'ha atacado con una patada voladora a'),
(44,'le ha echado acido en la cara a'),
(45,'le ha metido una rafaga de tiros a'),
(46,'ha deborado vivo a'),
(47,'le ha clavado un compas en los ojos a'),
(48,'le ha rajado las venas con la mariposa a'),
(49,'le ha vendido una bolsa de palomitas caducadas a'),
(50,'ha hervido vivo a'),
(51,'le ha refactorizado la cara de un guantazo a'),
(52,'ha cultivado Maria en el pecho de'),
(53,'ha hecho una barbacoa con su madre y'),
(54,'le ha dado de su doble V a'),
(55,'le ha partido el brazo a'),
(56,'le ha pagafanteado una BMX bomba a'),
(57,'ha hecho un musical con'),
(58,'atropella y se de a la fuga a');


INSERT INTO `counters`(`people1`, `people2`) VALUES 
(1,8),
(2,9),
(3,9),
(17,18),
(24,25),
(13,26),
(21,4),
(10,33),
(10,34),
(35,14),
(35,52),
(56,12),
(56,13),
(9,23),
(28,29),
(9,29),
(39,18),
(54,5),
(22,16),
(53,9),
(57,9);